title: Fernando Zapico # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks) 
  Passionate about technology, I love to create and do. From the origin of data, especially IoT, to its exploitation through Machine Learning, I enjoy the journey.  
  <br><br>
  I enjoy learning and developing projects.  
  <br><br>
  <a href="https://www.linkedin.com/in/fernando-zapico-martin/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
